fix improper symlink
brettcannon/microvenv pull request #33
Opened 2023-03-14 01:35 UTC by ur4t

2023-03-14 17:39 UTC, brettcannon commented
Can you explain why you consider the symlink "wrong"? I'm assuming because it's an absolute path, but I don't quite see how that's inaccurate.

2023-03-14 17:43 UTC, brettcannon commented
I found https://github.com/python/cpython/commit/581c29f8fe20a6d95f036a3499b55cc2c587b25f which documents that it's on purpose.

2023-03-14 17:47 UTC, brettcannon requested changes
Please add a test using `pathlib.Path.readlink()` to verify that the symlink is relative.

2023-03-15 00:49 UTC, ur4t commented
> Can you explain why you consider the symlink "wrong"? I'm assuming because it's an absolute path, but I don't quite see how that's inaccurate.

It is an absolute path in test cases, which is provided by `tmp_path_factory.mktemp()`. But we did not make `env_path` an absolute path when we simply run `python3 microvenv.py` (or with other relative path names).

I found this bug via running `python3 microvenv.py && readlink -f .venv/lib64`, which was failed because `.venv/lib64` was symlinked to a relative path `.venv/lib` then.

So I chose the title "fix improper symlink".

> I found [python/cpython@581c29f](https://github.com/python/cpython/commit/581c29f8fe20a6d95f036a3499b55cc2c587b25f) which documents that it's on purpose.

Great!

> Please add a test using `pathlib.Path.readlink()` to verify that the symlink is relative.

Added.

2023-03-15 18:38 UTC, brettcannon requested changes

2023-03-15 18:38 UTC, brettcannon commented on test_microvenv.py
> +        assert pathlib.Path.readlink(micro_lib64).is_relative_to("lib")
`is_relative_to()` is a bit too flexible to make sure this doesn't change, so I would prefer to be a bit strict about exactly what the symlink is set to.

```suggestion
        assert os.fsdecode(pathlib.Path.readlink(micro_lib64)) == "lib"
```

2023-03-15 18:43 UTC, brettcannon requested changes

2023-03-15 18:43 UTC, brettcannon commented on test_microvenv.py
> +        assert os.fsdecode(pathlib.Path.readlink(micro_lib64)) == "lib"
`pathlib.Path.readlink()` was added in Python 3.9.

```suggestion
        # pathlib.Path.readlink() was added in Python 3.9.
        assert os.readlink(micro_lib64) == "lib"
```

2023-03-15 18:48 UTC, merged

2023-03-15 18:48 UTC, brettcannon commented
Thanks for the PR!